SKILLS = [
    "python",
    "java",
    "c++",
    "sql",
    "machine learning",
    "deep learning",
    "data analysis",
    "tensorflow",
    "pytorch",
    "nlp",
    "aws",
    "azure",
    "docker",
    "kubernetes",
    "fastapi",
    "flask",
    "streamlit",
    "power bi",
    "tableau",
    "excel",
    "git",
    "github"
]